package com.fish.mirebound.mud;

import com.fish.mirebound.mud.harvest.MudHarvestTool;
import java.util.Arrays;

public enum MudPhysicsParameter {
    ENABLED(Target.ALL, Category.SHAPE, 0.0D, 1.0D, 1.0D, 0),
    SHAPE_TYPE(Target.ALL, Category.SHAPE, 0.0D, MudShapeType.values().length - 1.0D, 1.0D, 0),
    BEHAVIOR_PROFILE(Target.ALL, Category.SHAPE, 0.0D, MudBehaviorType.values().length - 1.0D, 1.0D, 0),
    SURFACE_HEIGHT(Target.ALL, Category.SHAPE, 0.0625D, 1.0D, 0.0625D, 4),
    POLLUTION_MULTIPLIER(Target.ALL, Category.COVERAGE, 0.0D, 4.0D, 0.05D, 2),
    WATER_WASH_MULTIPLIER(Target.ALL, Category.COVERAGE, 0.05D, 4.0D, 0.05D, 2),
    RAIN_WASH_MULTIPLIER(Target.ALL, Category.COVERAGE, 0.0D, 4.0D, 0.05D, 2),

    MAX_DEPTH_FACTOR(Target.ORDINARY, Category.SINKING, 0.0D, 2.50D, 0.01D, 2),
    COLUMN_MARGIN(Target.ORDINARY, Category.SINKING, 0.0D, 1.0D, 0.005D, 3),
    BASE_SINK_SPEED(Target.ORDINARY, Category.SINKING, 0.0D, 0.040D, 0.0005D, 4),
    DEEP_SINK_RATIO(Target.ORDINARY, Category.SINKING, 0.0D, 1.50D, 0.01D, 2),
    MAX_SINK_SPEED(Target.ORDINARY, Category.SINKING, 0.001D, 0.20D, 0.001D, 3),
    BRAKE_DISTANCE(Target.ORDINARY, Category.SINKING, 0.02D, 1.50D, 0.01D, 2),

    WALK_SURFACE(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.01D, 2),
    WALK_KNEE(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.01D, 2),
    WALK_THIGH(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.01D, 2),
    WALK_WAIST(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.005D, 3),
    VERTICAL_SURFACE(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.01D, 2),
    VERTICAL_DEEP(Target.ORDINARY, Category.MOVEMENT, 0.0D, 1.20D, 0.005D, 3),

    MOVEMENT_SINK_SCALE(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.30D, 0.001D, 3),
    CROUCH_SINK(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.040D, 0.0005D, 4),
    LOOK_SINK_SCALE(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.005D, 0.00001D, 5),
    HOLD_SINK(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.040D, 0.0005D, 4),
    AGITATION_SINK_SCALE(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.050D, 0.0005D, 4),
    STRUGGLE_MIN(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.40D, 0.005D, 3),
    STRUGGLE_MAX(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 0.70D, 0.005D, 3),
    STRUGGLE_DEEP_MULTIPLIER(Target.ORDINARY, Category.DISTURBANCE, 0.0D, 1.50D, 0.01D, 2),

    SLIME_MIN_COLUMN_DEPTH(Target.LIVING_SLIME, Category.SLIME_DEPTH, 0.10D, 3.0D, 0.05D, 2),
    SLIME_COLUMN_MARGIN(Target.LIVING_SLIME, Category.SLIME_DEPTH, 0.0D, 0.30D, 0.005D, 3),
    SLIME_REST_HEIGHT_FACTOR(Target.LIVING_SLIME, Category.SLIME_DEPTH, 0.0D, 1.50D, 0.01D, 2),
    SLIME_REST_COLUMN_FACTOR(Target.LIVING_SLIME, Category.SLIME_DEPTH, 0.0D, 1.50D, 0.01D, 2),
    SLIME_VERTICAL_SPRING(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 0.15D, 0.001D, 3),
    SLIME_VERTICAL_DAMPING(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 1.20D, 0.01D, 2),
    SLIME_BASE_SINK_BIAS(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 0.030D, 0.0001D, 4),
    SLIME_MOVEMENT_SINK_SCALE(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 0.15D, 0.001D, 3),
    SLIME_CROUCH_SINK(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 0.040D, 0.0005D, 4),
    SLIME_MAX_DOWN_SPEED(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.001D, 0.25D, 0.005D, 3),
    SLIME_MAX_UP_SPEED(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.001D, 2.00D, 0.005D, 3),
    SLIME_IMPACT_THRESHOLD(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 0.25D, 0.005D, 3),
    SLIME_IMPACT_RESTITUTION(Target.LIVING_SLIME, Category.SLIME_BOUNCE, 0.0D, 1.50D, 0.01D, 2),
    SLIME_WALK_SHALLOW(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 1.20D, 0.01D, 2),
    SLIME_WALK_DEEP(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 1.20D, 0.01D, 2),
    SLIME_ANCHOR_TUG_SHALLOW(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 0.40D, 0.005D, 3),
    SLIME_ANCHOR_TUG_DEEP(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 0.40D, 0.005D, 3),
    SLIME_ANCHOR_FOLLOW_SHALLOW(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 1.0D, 0.005D, 3),
    SLIME_ANCHOR_FOLLOW_DEEP(Target.LIVING_SLIME, Category.SLIME_ANCHOR, 0.0D, 1.0D, 0.005D, 3),
    SLIME_STRUGGLE_MIN(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 1.50D, 0.005D, 3),
    SLIME_STRUGGLE_MAX(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 1.50D, 0.005D, 3),
    SLIME_STRUGGLE_DEEP_MULTIPLIER(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 1.50D, 0.01D, 2),
    SLIME_STRUGGLE_EXISTING_UPWARD_RETENTION(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 1.0D, 0.01D, 2),
    SLIME_STRUGGLE_LIFT_TICKS_MIN(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 20.0D, 1.0D, 0),
    SLIME_STRUGGLE_LIFT_TICKS_MAX(Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 20.0D, 1.0D, 0),

    YIELD_THRESHOLD(Target.ORDINARY, Category.RHEOLOGY, 0.0D, 0.040D, 0.0001D, 4),
    YIELD_DEPTH_GAIN(Target.ORDINARY, Category.RHEOLOGY, 0.0D, 4.0D, 0.05D, 2),
    SETTLING_RESPONSE(Target.ORDINARY, Category.RHEOLOGY, 0.01D, 1.0D, 0.01D, 2),
    VISCOSITY_SURFACE(Target.ORDINARY, Category.RHEOLOGY, 0.10D, 8.0D, 0.05D, 2),
    VISCOSITY_DEEP(Target.ORDINARY, Category.RHEOLOGY, 0.10D, 12.0D, 0.05D, 2),
    YIELD_SOFTNESS(Target.ORDINARY, Category.RHEOLOGY, 0.0001D, 0.030D, 0.0001D, 4),
    DISTURBANCE_YIELD_REDUCTION(Target.ORDINARY, Category.RHEOLOGY, 0.0D, 1.0D, 0.01D, 2),
    CAP_STOP_RESPONSE(Target.ORDINARY, Category.RHEOLOGY, 0.01D, 1.0D, 0.01D, 2),

    TENTACLE_MAX_INSTANCES(Target.TENTACLE, Category.TENTACLE_LIFECYCLE, 1.0D, 128.0D, 1.0D, 0),
    TENTACLE_MAX_VOLUME(Target.TENTACLE, Category.TENTACLE_LIFECYCLE, 0.125D, 125.0D, 0.125D, 3),

    TENTACLE_SEGMENTS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 6.0D, 32.0D, 1.0D, 0),
    TENTACLE_SEGMENT_LENGTH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.10D, 0.50D, 0.01D, 2),
    TENTACLE_ROOT_RADIUS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.04D, 0.40D, 0.01D, 2),
    TENTACLE_TIP_RADIUS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.02D, 0.30D, 0.01D, 2),
    TENTACLE_GRAVITY(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.05D, 0.0005D, 4),
    TENTACLE_DAMPING(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.50D, 0.999D, 0.005D, 3),
    TENTACLE_STRETCH_COMPLIANCE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.05D, 0.00001D, 5),
    TENTACLE_SOLVER_STRETCH_LIMIT(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 1.75D, 0.01D, 2),
    TENTACLE_BEND_COMPLIANCE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.10D, 0.0001D, 4),
    TENTACLE_CURVATURE_SMOOTHING(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.95D, 0.01D, 2),
    TENTACLE_BEND_REST_RATIO(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.50D, 0.999D, 0.005D, 3),
    TENTACLE_TIP_BEND_FLEXIBILITY(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 6.0D, 0.10D, 2),
    TENTACLE_SELF_COLLISION_ENABLED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 1.0D, 1.0D, 0),
    TENTACLE_SELF_COLLISION_RADIUS_SCALE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.40D, 1.50D, 0.05D, 2),
    TENTACLE_SELF_COLLISION_RESPONSE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 1.0D, 0.05D, 2),
    TENTACLE_SUBSTEPS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 4.0D, 1.0D, 0),
    TENTACLE_ITERATIONS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 12.0D, 1.0D, 0),
    TENTACLE_EMERGE_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.005D, 0.25D, 0.005D, 3),
    TENTACLE_RETRACT_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.005D, 0.30D, 0.005D, 3),
    TENTACLE_IDLE_REACH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.25D, 12.0D, 0.05D, 2),
    TENTACLE_IDLE_HEIGHT(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 4.0D, 0.05D, 2),
    TENTACLE_IDLE_SWAY(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 1.5D, 0.05D, 2),
    TENTACLE_IDLE_SWAY_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.50D, 0.005D, 3),
    TENTACLE_IDLE_DECISION_TICKS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 10.0D, 240.0D, 1.0D, 0),
    TENTACLE_IDLE_MIN_REACH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.95D, 0.01D, 2),
    TENTACLE_IDLE_MAX_REACH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.05D, 1.25D, 0.01D, 2),
    TENTACLE_IDLE_REST_RATIO(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.90D, 0.01D, 2),
    TENTACLE_LENGTH_VARIATION(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.45D, 0.01D, 2),
    TENTACLE_THICKNESS_VARIATION(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.45D, 0.01D, 2),
    TENTACLE_VOLUME_LENGTH_EXPONENT(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.333D, 0.85D, 0.01D, 3),
    TENTACLE_THICKNESS_LENGTH_COUPLING(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 1.50D, 0.05D, 2),
    TENTACLE_MOTION_VARIATION(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.45D, 0.01D, 2),
    TENTACLE_MUSCLE_AMPLITUDE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.60D, 0.01D, 2),
    TENTACLE_MUSCLE_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.50D, 0.005D, 3),
    TENTACLE_GUIDE_STRENGTH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.50D, 0.005D, 3),
    TENTACLE_GUIDE_DEAD_ZONE_SCALE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 3.0D, 0.05D, 2),
    TENTACLE_GUIDE_INERTIA_TRANSFER(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.90D, 0.05D, 2),
    TENTACLE_TIP_ORIENTATION_STRENGTH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 1.0D, 0.01D, 2),
    TENTACLE_TIP_ORIENTATION_SEGMENTS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 2.0D, 8.0D, 1.0D, 0),
    TENTACLE_TIP_ACCELERATION(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.001D, 0.50D, 0.005D, 3),
    TENTACLE_TIP_LOOKAHEAD_SEGMENTS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.50D, 8.0D, 0.25D, 2),
    TENTACLE_TIP_MAX_LEAD_SEGMENTS(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.50D, 8.0D, 0.25D, 2),
    TENTACLE_TIP_ADVANCE_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.005D, 0.50D, 0.005D, 3),
    TENTACLE_TRACK_TIP_ADVANCE_SPEED(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.01D, 1.50D, 0.01D, 2),
    TENTACLE_TRACK_MAX_STRETCH(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 1.60D, 0.01D, 2),
    TENTACLE_LENGTH_RESPONSE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.005D, 0.30D, 0.005D, 3),
    TENTACLE_SLACK_CURVE(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.75D, 0.01D, 2),
    TENTACLE_CURVE_WAVES(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 1.0D, 4.0D, 1.0D, 0),
    TENTACLE_CURVE_DETAIL(Target.TENTACLE, Category.TENTACLE_DYNAMICS, 0.0D, 0.75D, 0.01D, 2),

    TENTACLE_PATH_CELL_SIZE(Target.TENTACLE, Category.TENTACLE_PATH, 0.25D, 1.0D, 0.05D, 2),
    TENTACLE_PATH_CLEARANCE(Target.TENTACLE, Category.TENTACLE_PATH, 0.01D, 0.50D, 0.01D, 2),
    TENTACLE_PATH_TIP_CLEARANCE_SCALE(Target.TENTACLE, Category.TENTACLE_PATH, 0.50D, 2.0D, 0.05D, 2),
    TENTACLE_PATH_MARGIN(Target.TENTACLE, Category.TENTACLE_PATH, 0.5D, 4.0D, 0.25D, 2),
    TENTACLE_PATH_REPLAN_TICKS(Target.TENTACLE, Category.TENTACLE_PATH, 2.0D, 40.0D, 1.0D, 0),
    TENTACLE_STUCK_REPLAN_TICKS(Target.TENTACLE, Category.TENTACLE_PATH, 10.0D, 200.0D, 5.0D, 0),
    TENTACLE_STUCK_PROGRESS_DISTANCE(Target.TENTACLE, Category.TENTACLE_PATH, 0.01D, 1.0D, 0.01D, 2),
    TENTACLE_STUCK_CLEARANCE_STEPS(Target.TENTACLE, Category.TENTACLE_PATH, 1.0D, 8.0D, 1.0D, 0),
    TENTACLE_PATH_MAX_NODES(Target.TENTACLE, Category.TENTACLE_PATH, 128.0D, 8192.0D, 128.0D, 0),
    TENTACLE_PATH_GOAL_TOLERANCE(Target.TENTACLE, Category.TENTACLE_PATH, 0.05D, 2.0D, 0.05D, 2),
    TENTACLE_PATH_REPAIR_LOOKAHEAD(Target.TENTACLE, Category.TENTACLE_PATH, 1.0D, 8.0D, 1.0D, 0),
    TENTACLE_TRAIL_SAMPLE_DISTANCE_SCALE(Target.TENTACLE, Category.TENTACLE_PATH, 0.10D, 2.0D, 0.05D, 2),
    TENTACLE_TRAIL_UNWRAP_TICKS(Target.TENTACLE, Category.TENTACLE_PATH, 1.0D, 40.0D, 1.0D, 0),
    TENTACLE_TRAIL_MAX_POINTS(Target.TENTACLE, Category.TENTACLE_PATH, 32.0D, 256.0D, 8.0D, 0),
    TENTACLE_TRAIL_RELEASE_RATIO(Target.TENTACLE, Category.TENTACLE_PATH, 0.70D, 1.20D, 0.01D, 2),
    TENTACLE_COLLISION_SLOP(Target.TENTACLE, Category.TENTACLE_PATH, 0.0001D, 0.05D, 0.001D, 4),
    TENTACLE_ENTITY_COLLISION_ENABLED(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 1.0D, 1.0D, 0),
    TENTACLE_COLLISION_RESPONSE(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 1.0D, 0.01D, 2),
    TENTACLE_COLLISION_IMPULSE(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 0.50D, 0.005D, 3),
    TENTACLE_COLLISION_MAX_PUSH_SPEED(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 0.75D, 0.01D, 2),
    TENTACLE_BODY_COMPLIANCE(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 1.0D, 0.01D, 2),
    TENTACLE_BODY_MAX_DEFLECTION(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 0.75D, 0.01D, 2),
    TENTACLE_SIZE_FORCE_EXPONENT(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 2.0D, 0.05D, 2),
    TENTACLE_SIZE_STIFFNESS_EXPONENT(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 2.0D, 0.05D, 2),
    TENTACLE_COLLISION_MAX_ENTITIES(Target.TENTACLE, Category.TENTACLE_PATH, 0.0D, 64.0D, 1.0D, 0),
    TENTACLE_ENTITY_QUERY_INTERVAL(Target.TENTACLE, Category.TENTACLE_PATH, 1.0D, 20.0D, 1.0D, 0),
    TENTACLE_COLLISION_MAX_BLOCK_SAMPLES(Target.TENTACLE, Category.TENTACLE_PATH, 256.0D, 32768.0D, 256.0D, 0),
    TENTACLE_SYNC_INTERVAL_TICKS(Target.TENTACLE, Category.TENTACLE_PATH, 1.0D, 10.0D, 1.0D, 0),

    TENTACLE_GRAB_TIP_SEGMENTS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 8.0D, 1.0D, 0),
    TENTACLE_GRAB_CONTACT_PADDING(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 1.0D, 0.01D, 2),
    TENTACLE_GRAB_TARGET_PADDING_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 1.0D, 0.05D, 2),
    TENTACLE_GRAB_ATTACH_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 100.0D, 1.0D, 0),
    TENTACLE_GRAB_SPRING(Target.TENTACLE, Category.TENTACLE_GRAB, 0.01D, 1.0D, 0.01D, 2),
    TENTACLE_GRAB_DAMPING(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 0.95D, 0.01D, 2),
    TENTACLE_GRAB_MAX_ACCELERATION(Target.TENTACLE, Category.TENTACLE_GRAB, 0.01D, 1.0D, 0.01D, 2),
    TENTACLE_GRAB_MAX_SPEED(Target.TENTACLE, Category.TENTACLE_GRAB, 0.05D, 3.0D, 0.05D, 2),
    TENTACLE_GRAB_BREAK_DISTANCE(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 32.0D, 0.5D, 2),
    TENTACLE_GRAB_MAX_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 2400.0D, 20.0D, 0),
    TENTACLE_GRAB_WHOLE_BODY_TIP_RATIO(Target.TENTACLE, Category.TENTACLE_GRAB, 0.10D, 1.50D, 0.05D, 2),
    TENTACLE_GRAB_SURFACE_CLEARANCE_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.50D, 2.0D, 0.05D, 2),
    TENTACLE_GRAB_FLIGHT_CONTROL_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.10D, 1.0D, 0.05D, 2),
    TENTACLE_HOLD_WRAP_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 200.0D, 1.0D, 0),
    TENTACLE_HOLD_LIFT_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 200.0D, 1.0D, 0),
    TENTACLE_HOLD_LIFT_HEIGHT(Target.TENTACLE, Category.TENTACLE_GRAB, 0.25D, 8.0D, 0.25D, 2),
    TENTACLE_HOLD_CONTROL_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.10D, 1.0D, 0.05D, 2),
    TENTACLE_RAGDOLL_GRAVITY(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 0.12D, 0.001D, 3),
    TENTACLE_RAGDOLL_ARM_GRAVITY_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.50D, 5.0D, 0.05D, 2),
    TENTACLE_RAGDOLL_ARM_TORSO_CLEARANCE_SCALE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.50D, 2.0D, 0.05D, 2),
    TENTACLE_RAGDOLL_DAMPING(Target.TENTACLE, Category.TENTACLE_GRAB, 0.50D, 0.999D, 0.005D, 3),
    TENTACLE_RAGDOLL_INERTIA(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 2.0D, 0.05D, 2),
    TENTACLE_RAGDOLL_GRIP_STIFFNESS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.05D, 1.0D, 0.01D, 2),
    TENTACLE_RAGDOLL_GRIP_ORIENTATION_STIFFNESS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 1.0D, 0.01D, 2),
    TENTACLE_RAGDOLL_JOINT_STIFFNESS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.05D, 1.0D, 0.01D, 2),
    TENTACLE_RAGDOLL_SOLVER_ITERATIONS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 12.0D, 1.0D, 0),
    TENTACLE_RAGDOLL_COLLISION_ENABLED(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 1.0D, 1.0D, 0),
    TENTACLE_RAGDOLL_COLLISION_RADIUS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.02D, 0.30D, 0.01D, 2),
    TENTACLE_RAGDOLL_MAX_NODE_SPEED(Target.TENTACLE, Category.TENTACLE_GRAB, 0.05D, 2.0D, 0.05D, 2),
    TENTACLE_THRASH_RADIUS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.25D, 12.0D, 0.25D, 2),
    TENTACLE_THRASH_VERTICAL_RANGE(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 8.0D, 0.25D, 2),
    TENTACLE_THRASH_SPEED(Target.TENTACLE, Category.TENTACLE_GRAB, 0.005D, 1.0D, 0.005D, 3),
    TENTACLE_THRASH_JITTER(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 3.0D, 0.05D, 2),
    TENTACLE_WRAP_RADIUS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.20D, 3.0D, 0.05D, 2),
    TENTACLE_WRAP_SPEED(Target.TENTACLE, Category.TENTACLE_GRAB, 0.005D, 1.0D, 0.005D, 3),

    SWARM_RADIUS(Target.SWARM, Category.SWARM, 0.5D, 12.0D, 0.25D, 2),
    SWARM_BUILDUP(Target.SWARM, Category.SWARM, 0.001D, 0.25D, 0.001D, 3),
    SWARM_DECAY(Target.SWARM, Category.SWARM, 0.001D, 0.25D, 0.001D, 3),
    SWARM_WATER_DECAY(Target.SWARM, Category.SWARM, 0.001D, 1.0D, 0.01D, 2),
    SWARM_MOVE_SCALE(Target.SWARM, Category.SWARM, 0.1D, 1.0D, 0.01D, 2),
    SWARM_STRUGGLE_SCALE(Target.SWARM, Category.SWARM, 0.1D, 1.0D, 0.01D, 2),
    SWARM_MAX_SCREEN_INSECTS(Target.SWARM, Category.SWARM, 0.0D, 64.0D, 1.0D, 0),
    SWARM_SCREEN_OPACITY(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 0.05D, 2),
    SWARM_SCREEN_SPEED(Target.SWARM, Category.SWARM, 0.1D, 4.0D, 0.05D, 2),
    SWARM_CLEAR_ON_DEATH(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 1.0D, 0),
    SWARM_CLEAR_ON_RECONNECT(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 1.0D, 0),

    TENTACLE_HOLD_POSITION_RADIUS(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 8.0D, 0.25D, 2),
    TENTACLE_HOLD_HEIGHT_VARIATION(Target.TENTACLE, Category.TENTACLE_GRAB, 0.0D, 4.0D, 0.25D, 2),
    TENTACLE_HOLD_POSITION_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 20.0D, 600.0D, 10.0D, 0),
    TENTACLE_HOLD_MOVE_TICKS(Target.TENTACLE, Category.TENTACLE_GRAB, 1.0D, 200.0D, 5.0D, 0),

    // Appended to preserve the ordinals of existing saved/networked parameters.
    WALK_KNEE_DEPTH(Target.ORDINARY, Category.MOVEMENT, 0.05D, 0.45D, 0.01D, 2),
    WALK_THIGH_DEPTH(Target.ORDINARY, Category.MOVEMENT, 0.10D, 0.65D, 0.01D, 2),
    WALK_WAIST_DEPTH(Target.ORDINARY, Category.MOVEMENT, 0.20D, 0.85D, 0.01D, 2),

    // Appended so existing saved/networked parameter ordinals remain stable.
    SURFACE_EFFECTS_ENABLED(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 1.0D, 1.0D, 0),
    SURFACE_HOLE_RADIUS_SCALE(Target.ALL, Category.SURFACE_EFFECTS, 0.25D, 2.50D, 0.05D, 2),
    SURFACE_HOLE_DARKENING(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 0.85D, 0.01D, 2),
    SURFACE_RIM_WIDTH_PIXELS(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 4.0D, 0.25D, 2),
    SURFACE_RIM_HEIGHT_PIXELS(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 3.0D, 0.25D, 2),
    SURFACE_CLOSE_TICKS(Target.ALL, Category.SURFACE_EFFECTS, 5.0D, 240.0D, 1.0D, 0),
    SURFACE_MOVEMENT_TRAIL(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 1.0D, 0.05D, 2),
    SURFACE_BUBBLE_RATE(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 0.50D, 0.005D, 3),
    SURFACE_BUBBLE_MIN_PIXELS(Target.ALL, Category.SURFACE_EFFECTS, 0.5D, 8.0D, 0.25D, 2),
    SURFACE_BUBBLE_MAX_PIXELS(Target.ALL, Category.SURFACE_EFFECTS, 0.5D, 12.0D, 0.25D, 2),
    SURFACE_BUBBLE_SOUND_VOLUME(Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 1.0D, 0.01D, 2),
    SURFACE_BUBBLE_SOUND_PITCH(Target.ALL, Category.SURFACE_EFFECTS, 0.25D, 2.0D, 0.05D, 2),

    // Fixed-pixel surface height-field parameters. Appended for ordinal stability.
    SURFACE_DISPLACEMENT_PIXELS(Target.ALL, Category.SURFACE_EFFECTS, 0.05D, 2.0D, 0.05D, 2),
    SURFACE_HEIGHT_RESPONSE(Target.ALL, Category.SURFACE_EFFECTS, 0.02D, 0.60D, 0.01D, 2),

    // Composable ordinary-medium behavior weights. Appended for ordinal stability.
    GRANULAR_COLLAPSE(Target.ORDINARY, Category.BEHAVIOR_COMPONENTS, 0.0D, 2.0D, 0.05D, 2),
    COHESIVE_SUCTION(Target.ORDINARY, Category.BEHAVIOR_COMPONENTS, 0.0D, 2.0D, 0.05D, 2),
    ADHESIVE_GRIP(Target.ORDINARY, Category.BEHAVIOR_COMPONENTS, 0.0D, 2.0D, 0.05D, 2),

    // Additional rim reach created by a high-energy impact.
    SURFACE_IMPACT_PILE_EXPANSION_PIXELS(
            Target.ALL, Category.SURFACE_EFFECTS, 0.0D, 8.0D, 0.25D, 2),

    // Appended swarm presentation controls. Keep these after all existing values
    // so saved profile arrays retain their previous parameter ordinals.
    SWARM_INSECT_SCALE(Target.SWARM, Category.SWARM, 0.50D, 3.0D, 0.05D, 2),
    SWARM_INSECT_WANDER(Target.SWARM, Category.SWARM, 0.0D, 2.0D, 0.05D, 2),
    SWARM_SILK_DENSITY(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 0.05D, 2),
    SWARM_SILK_OPACITY(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 0.05D, 2),
    SWARM_SILK_REACH(Target.SWARM, Category.SWARM, 0.10D, 0.80D, 0.05D, 2),

    // Swarm removal and crawler lifetime controls, appended for profile compatibility.
    SWARM_SHAKE_THRESHOLD(Target.SWARM, Category.SWARM, 0.0D, 180.0D, 1.0D, 0),
    SWARM_SHAKE_REMOVAL(Target.SWARM, Category.SWARM, 0.0001D, 0.020D, 0.0001D, 4),
    SWARM_SCREEN_LIFETIME(Target.SWARM, Category.SWARM, 20.0D, 200.0D, 5.0D, 0),
    SWARM_DROP_ACCELERATION(Target.SWARM, Category.SWARM, 0.001D, 0.120D, 0.001D, 3),

    // Reusable adhesion templates. Appended for profile ordinal stability.
    ADHESION_STRANDS_ENABLED(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 1.0D, 1.0D, 0),
    ADHESION_STRAND_MIN_COUNT(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 16.0D, 1.0D, 0),
    ADHESION_STRAND_MAX_COUNT(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 16.0D, 1.0D, 0),
    ADHESION_STRAND_MIN_COVERAGE(Target.ALL, Category.ADHESION_STRANDS, 0.01D, 1.0D, 0.01D, 2),
    ADHESION_STRAND_WIDTH_PIXELS(Target.ALL, Category.ADHESION_STRANDS, 0.15D, 3.0D, 0.05D, 2),
    ADHESION_STRAND_BREAK_LENGTH(Target.ALL, Category.ADHESION_STRANDS, 0.15D, 6.0D, 0.05D, 2),
    ADHESION_STRAND_CURVE(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 1.0D, 0.05D, 2),
    ADHESION_STRAND_RETRACT_TICKS(Target.ALL, Category.ADHESION_STRANDS, 2.0D, 60.0D, 1.0D, 0),

    // Motion-driven oil bridge controls. Appended for saved/networked ordinal stability.
    ADHESION_STRAND_INERTIA(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.98D, 0.01D, 2),
    ADHESION_STRAND_RESPONSE(Target.ALL, Category.ADHESION_STRANDS, 0.02D, 1.0D, 0.01D, 2),
    ADHESION_STRAND_NECK_SCALE(Target.ALL, Category.ADHESION_STRANDS, 0.10D, 1.0D, 0.05D, 2),
    ADHESION_STRAND_END_WIDTH_SCALE(Target.ALL, Category.ADHESION_STRANDS, 0.50D, 2.50D, 0.05D, 2),
    ADHESION_STRAND_SPAWN_HEIGHT(Target.ALL, Category.ADHESION_STRANDS, 0.05D, 2.50D, 0.05D, 2),

    // Broad viscous-sheet stage before an adhesive bridge separates into fingers.
    ADHESION_SHEET_ENABLED(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 1.0D, 1.0D, 0),
    ADHESION_SHEET_MIN_RIBS(Target.ALL, Category.ADHESION_STRANDS, 2.0D, 8.0D, 1.0D, 0),
    ADHESION_SHEET_MAX_SPAN(Target.ALL, Category.ADHESION_STRANDS, 0.10D, 2.0D, 0.05D, 2),
    ADHESION_SHEET_FINGERING_START(Target.ALL, Category.ADHESION_STRANDS, 0.10D, 0.95D, 0.05D, 2),
    ADHESION_SHEET_IRREGULARITY(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 1.0D, 0.05D, 2),

    // Appended so existing saved/networked parameter ordinals remain stable.
    COVERAGE_MAXIMUM(Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 0.05D, 2),
    COVERAGE_OPACITY_VARIATION(Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 0.05D, 2),
    COVERAGE_OPACITY(Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 0.05D, 2),
    AUTO_STACK_FILL(Target.ALL, Category.SHAPE, 0.0D, 1.0D, 1.0D, 0),
    COVERAGE_NATURAL_FADE_TICKS(Target.ALL, Category.COVERAGE, 0.0D, 72000.0D, 20.0D, 0),

    // Sculk mire owns a separate input-sensitive state machine. Appended for
    // saved profile and network ordinal compatibility.
    SCULK_SNEAK_WALK_SCALE(Target.SCULK, Category.SCULK, 0.10D, 1.20D, 0.05D, 2),
    SCULK_QUIET_CROUCH_DELAY_TICKS(Target.SCULK, Category.SCULK, 20.0D, 400.0D, 10.0D, 0),
    SCULK_QUIET_RISE_SPEED(Target.SCULK, Category.SCULK, 0.001D, 0.12D, 0.001D, 3),
    SCULK_ACTION_SINK_BOOST(Target.SCULK, Category.SCULK, 0.0D, 0.16D, 0.002D, 3),
    SCULK_ACTION_THRESHOLD(Target.SCULK, Category.SCULK, 0.01D, 0.50D, 0.01D, 2),
    SCULK_LOOK_ACTIVITY_THRESHOLD(Target.SCULK, Category.SCULK, 0.10D, 12.0D, 0.10D, 2),
    SCULK_HIDDEN_VALUE_GAIN(Target.SCULK, Category.SCULK, 0.001D, 0.10D, 0.001D, 3),
    SCULK_HIDDEN_VALUE_DECAY(Target.SCULK, Category.SCULK, 0.001D, 0.10D, 0.001D, 3),
    SCULK_TRIGGER_DEPTH(Target.SCULK, Category.SCULK, 0.02D, 0.75D, 0.01D, 2),
    SCULK_HIDDEN_TRIGGER_THRESHOLD(Target.SCULK, Category.SCULK, 0.10D, 5.0D, 0.05D, 2),
    SCULK_CLAMP_DURATION_TICKS(Target.SCULK, Category.SCULK, 20.0D, 600.0D, 10.0D, 0),
    SCULK_CLAMP_MAXIMUM_TICKS(Target.SCULK, Category.SCULK, 20.0D, 1200.0D, 10.0D, 0),
    SCULK_CLAMP_EXTENSION_TICKS(Target.SCULK, Category.SCULK, 1.0D, 20.0D, 1.0D, 0),
    SCULK_CLAMP_WALK_SCALE(Target.SCULK, Category.SCULK, 0.001D, 0.30D, 0.005D, 3),
    SCULK_RESONANCE_INTERVAL_TICKS(Target.SCULK, Category.SCULK, 1.0D, 40.0D, 1.0D, 0),
    SCULK_CLAMP_SYNC_INTERVAL_TICKS(Target.SCULK, Category.SCULK, 1.0D, 20.0D, 1.0D, 0),
    SCULK_CLAMP_EMERGE_TICKS(Target.SCULK, Category.SCULK, 2.0D, 60.0D, 1.0D, 0),
    SCULK_CLAMP_RETRACT_TICKS(Target.SCULK, Category.SCULK, 2.0D, 80.0D, 1.0D, 0),
    SCULK_CLAMP_RADIUS(Target.SCULK, Category.SCULK, 0.20D, 1.50D, 0.05D, 2),
    SCULK_CLAMP_HEIGHT(Target.SCULK, Category.SCULK, 0.15D, 1.50D, 0.05D, 2),
    SCULK_CLAMP_RENDER_DISTANCE(Target.SCULK, Category.SCULK, 16.0D, 192.0D, 8.0D, 0),
    SCULK_CLAMP_CLOSE_TICKS(Target.SCULK, Category.SCULK, 2.0D, 80.0D, 1.0D, 0),
    SCULK_CLAMP_OPEN_TICKS(Target.SCULK, Category.SCULK, 2.0D, 80.0D, 1.0D, 0),

    // Contractile tissue is layered over ordinary rheology. Appended so all
    // existing saved and networked parameter ordinals remain stable.
    FLESH_PULSE_PERIOD_TICKS(Target.TENDER_FLESH, Category.TENDER_FLESH, 20.0D, 240.0D, 1.0D, 0),
    FLESH_CONTRACTION_STRENGTH(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.01D, 2),
    FLESH_WRAP_GAIN(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.001D, 0.10D, 0.001D, 3),
    FLESH_WRAP_DECAY(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.001D, 0.10D, 0.001D, 3),
    FLESH_ACTIVITY_THRESHOLD(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.001D, 0.50D, 0.005D, 3),
    FLESH_WRAP_MOVEMENT_RESISTANCE(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.01D, 2),
    FLESH_CONTRACTION_SINK_SPEED(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 0.08D, 0.001D, 3),
    FLESH_ESCAPE_RELAXATION_THRESHOLD(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 0.95D, 0.01D, 2),
    FLESH_ESCAPE_BAD_MULTIPLIER(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.50D, 0.05D, 2),
    FLESH_ESCAPE_GOOD_MULTIPLIER(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 2.0D, 0.05D, 2),
    FLESH_SURFACE_PULSE_STRENGTH(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.05D, 2),
    FLESH_SOUND_VOLUME(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.01D, 2),

    // Geometric adhesion ring controls. Appended to preserve all old ordinals.
    ADHESION_RING_RADIUS(Target.ALL, Category.ADHESION_STRANDS, 0.10D, 2.50D, 0.01D, 2),
    ADHESION_RING_VARIATION(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.50D, 0.01D, 2),
    ADHESION_BODY_SLIDE_SPEED(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.08D, 0.001D, 3),
    ADHESION_RING_REFRESH_TICKS(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 20.0D, 1.0D, 0),
    ADHESION_GEOMETRIC_ANCHORS(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 1.0D, 1.0D, 0),
    ADHESION_RING_CLEARANCE(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.75D, 0.01D, 2),
    ADHESION_RING_DRIFT_AMOUNT(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.35D, 0.01D, 2),
    ADHESION_RING_DRIFT_SPEED(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 0.20D, 0.005D, 3),
    ADHESION_BODY_ANCHOR_LIFT(Target.ALL, Category.ADHESION_STRANDS, 0.03D, 0.50D, 0.01D, 2),

    // Adhesion lifecycle controls. Appended so existing profile ordinals stay stable.
    ADHESION_ATTACH_DELAY_TICKS(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 80.0D, 1.0D, 0),
    ADHESION_ATTACH_GROW_TICKS(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 80.0D, 1.0D, 0),
    ADHESION_SPAWN_INTERVAL_TICKS(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 20.0D, 1.0D, 0),
    ADHESION_ANCHOR_GRACE_TICKS(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 100.0D, 1.0D, 0),
    ADHESION_BREAK_CONFIRM_TICKS(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 30.0D, 1.0D, 0),
    ADHESION_ANCHOR_SEARCH_PIXELS(Target.ALL, Category.ADHESION_STRANDS, 0.0D, 4.0D, 1.0D, 0),

    // Number of well-distributed bridges created when stable contact begins.
    ADHESION_INITIAL_COUNT(Target.ALL, Category.ADHESION_STRANDS, 1.0D, 16.0D, 1.0D, 0),

    // Release feedback controls. Appended so every older saved/networked
    // parameter keeps its original ordinal.
    FLESH_RELEASE_OPPORTUNITY_THRESHOLD(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.05D, 2),
    FLESH_GOOD_RELEASE_WRAP_LOSS(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.01D, 2),
    FLESH_BAD_RELEASE_WRAP_GAIN(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 0.50D, 0.01D, 2),
    FLESH_ESCAPE_PULSE_SPEED(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 0.55D, 0.01D, 2),
    FLESH_ESCAPE_PULSE_TICKS(Target.TENDER_FLESH, Category.TENDER_FLESH, 1.0D, 12.0D, 1.0D, 0),
    FLESH_ESCAPE_PULSE_DAMPING(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.40D, 0.98D, 0.01D, 2),

    // Tender flesh pressure and visible fold controls. Appended to preserve
    // every existing saved and synchronized parameter ordinal.
    FLESH_PRESSURE_GAIN(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.001D, 0.12D, 0.001D, 3),
    FLESH_PRESSURE_DECAY(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.001D, 0.10D, 0.001D, 3),
    FLESH_PRESSURE_RESISTANCE(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 0.01D, 2),
    FLESH_PRESSURE_SINK_SPEED(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 0.08D, 0.001D, 3),
    FLESH_FOLD_HEIGHT_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.25D, 6.0D, 0.25D, 2),
    FLESH_FOLD_WIDTH_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.25D, 4.0D, 0.25D, 2),
    FLESH_FOLD_COUNT(Target.TENDER_FLESH, Category.TENDER_FLESH, 3.0D, 8.0D, 1.0D, 0),
    FLESH_TENTACLE_LENGTH_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH, 1.0D, 12.0D, 0.25D, 2),
    FLESH_TENTACLE_SWAY_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 4.0D, 0.25D, 2),
    FLESH_TENTACLE_SEGMENTS(Target.TENDER_FLESH, Category.TENDER_FLESH, 2.0D, 6.0D, 1.0D, 0),
    FLESH_TENTACLE_HEIGHT_SCALE(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.65D, 1.40D, 0.05D, 2),

    // Enclosure lifecycle and pool qualification. Kept as profile values so
    // local block overrides and world tuning use the same visual contract.
    FLESH_ENCLOSURE_WALK_SCALE_THRESHOLD(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.01D, 0.30D, 0.01D, 2),
    FLESH_ENCLOSURE_RISE_RATE(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.005D, 0.20D, 0.005D, 3),
    FLESH_ENCLOSURE_WITHDRAW_RATE(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.005D, 0.20D, 0.005D, 3),
    FLESH_ENCLOSURE_MIN_LAYERS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            1.0D, 4.0D, 1.0D, 0),
    FLESH_ENCLOSURE_MIN_POOL_WIDTH(Target.TENDER_FLESH, Category.TENDER_FLESH,
            1.0D, 4.0D, 1.0D, 0),
    FLESH_MEMBRANE_OPACITY(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.10D, 0.90D, 0.05D, 2),

    // Server-authoritative virtual collision for the procedural enclosure.
    FLESH_ENCLOSURE_COLLISION_START(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.0D, 0.95D, 0.05D, 2),
    FLESH_ENCLOSURE_OPEN_RADIUS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.10D, 1.0D, 0.01D, 2),
    FLESH_ENCLOSURE_CLOSED_RADIUS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.01D, 0.30D, 0.01D, 2),

    // Attackable enclosure lifecycle. Appended so existing profile ordinals remain stable.
    FLESH_ENCLOSURE_HEIGHT_MARGIN_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.0D, 8.0D, 0.25D, 2),
    FLESH_ENCLOSURE_MAX_HEIGHT_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            16.0D, 64.0D, 1.0D, 0),
    FLESH_ENCLOSURE_COOLDOWN_TICKS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            20.0D, 2400.0D, 20.0D, 0),
    FLESH_ENCLOSURE_STRIKE_COOLDOWN_TICKS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            1.0D, 20.0D, 1.0D, 0),

    // Struggle response controls appended to preserve every existing
    // saved/networked parameter ordinal.
    STRUGGLE_SINK_SUPPRESSION(Target.ORDINARY, Category.DISTURBANCE,
            0.0D, 1.0D, 0.01D, 2),
    STRUGGLE_LIFT_TICKS(Target.ORDINARY, Category.DISTURBANCE,
            1.0D, 8.0D, 1.0D, 0),
    FLESH_STRUGGLE_SINK_SUPPRESSION(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.0D, 1.0D, 0.01D, 2),
    FLESH_MEMBRANE_OPAQUE(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.0D, 1.0D, 1.0D, 0),

    // Appended to preserve every existing saved/networked parameter ordinal.
    FLESH_ENCLOSURE_MIN_HEIGHT_PIXELS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            4.0D, 48.0D, 1.0D, 0),
    FLESH_ENCLOSURE_FORCED_RELEASE_DISTANCE(Target.TENDER_FLESH, Category.TENDER_FLESH,
            0.25D, 8.0D, 0.05D, 2),

    // Per-pillar durability. Three bits per pillar are used by runtime/network state.
    FLESH_ENCLOSURE_MIN_PILLAR_HITS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            1.0D, 6.0D, 1.0D, 0),
    FLESH_ENCLOSURE_MAX_PILLAR_HITS(Target.TENDER_FLESH, Category.TENDER_FLESH,
            1.0D, 6.0D, 1.0D, 0),

    // Reusable assimilation template. Keep this complete block append-only:
    // local profiles persist parameter ordinals directly.
    ASSIMILATION_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_GAIN_PER_TICK(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.00001D, 0.05D, 0.0001D, 5),
    ASSIMILATION_IMMERSION_EXPONENT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.10D, 4.0D, 0.05D, 2),
    ASSIMILATION_MINIMUM_MOVE_SCALE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_MINIMUM_LOOK_SCALE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.02D, 1.0D, 0.01D, 2),
    ASSIMILATION_MINIMUM_ANIMATION_SCALE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SCREEN_OPACITY(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_BLUR_STRENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_ARMOR_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_ORDINARY_COVERAGE_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_FINAL_STASIS_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_SHELL_PHYSICS_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_SHELL_GRAVITY(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 0.30D, 0.005D, 3),
    ASSIMILATION_SHELL_AIR_DRAG(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SHELL_GROUND_FRICTION(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SHELL_RESTITUTION(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SHELL_MAXIMUM_SPEED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.05D, 20.0D, 0.05D, 2),
    ASSIMILATION_SHELL_MAXIMUM_TILT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 75.0D, 1.0D, 0),
    ASSIMILATION_SHELL_TILT_RESPONSE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.01D, 1.0D, 0.01D, 2),
    ASSIMILATION_SHELL_TELEPORT_RELEASE_DISTANCE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            4.0D, 1024.0D, 1.0D, 0),
    ASSIMILATION_SHELL_TRANSPORT_HANDOFF_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CORE,
            0.0D, 40.0D, 1.0D, 0),

    ASSIMILATION_SOUL_RADIUS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            4.0D, 128.0D, 1.0D, 0),
    ASSIMILATION_SOUL_MOVE_SPEED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.02D, 2.0D, 0.01D, 2),
    ASSIMILATION_SOUL_SPRINT_MULTIPLIER(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            1.0D, 4.0D, 0.05D, 2),
    ASSIMILATION_SOUL_ACCELERATION(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.05D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_DRAG(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 0.99D, 0.01D, 2),
    ASSIMILATION_SOUL_EMERGENCE_BACK_OFFSET(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 6.0D, 0.05D, 2),
    ASSIMILATION_SOUL_EMERGENCE_UP_OFFSET(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            -2.0D, 6.0D, 0.05D, 2),
    ASSIMILATION_SOUL_BASE_EFFECT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_EFFECT_START(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 0.95D, 0.01D, 2),
    ASSIMILATION_SOUL_COLOR_STRENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_PIXEL_SIZE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            1.0D, 16.0D, 0.25D, 2),
    ASSIMILATION_SOUL_BLUR_RADIUS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 8.0D, 0.25D, 2),
    ASSIMILATION_SOUL_BASE_FOG_STRENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_FOG_START(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 0.95D, 0.01D, 2),
    ASSIMILATION_SOUL_FOG_DISTANCE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            1.0D, 64.0D, 0.5D, 1),
    ASSIMILATION_SOUL_FOG_OPACITY(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_BOUNDARY_SOFTNESS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 0.75D, 0.01D, 2),
    ASSIMILATION_SOUL_FLOAT_AMPLITUDE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 0.25D, 0.005D, 3),
    ASSIMILATION_SOUL_FLOAT_SPEED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.005D, 0.50D, 0.005D, 3),
    ASSIMILATION_SOUL_SOUND_DAMPING(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SOUL_TRANSITION_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            0.0D, 100.0D, 1.0D, 0),
    ASSIMILATION_RESTORE_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            4.0D, 200.0D, 1.0D, 0),
    ASSIMILATION_RESTORE_BLACKOUT_FADE_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_SOUL,
            1.0D, 100.0D, 1.0D, 0),

    ASSIMILATION_RESCUE_PULSE_STRENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_RESCUE_CRACK_DARKNESS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_RESCUE_DAMAGE_PER_HIT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.005D, 1.0D, 0.005D, 3),
    ASSIMILATION_RESCUE_REVEAL_RADIUS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 6.0D, 1.0D, 0),
    ASSIMILATION_RESCUE_PULSE_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            1.0D, 40.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_TIMEOUT_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            10.0D, 200.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_NEXT_DELAY_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 100.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_FAILURE_DELAY_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 200.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_REQUIRED_STREAK(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            1.0D, 32.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_REVEAL_RADIUS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 6.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_FADE_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            1.0D, 60.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_AIM_DEGREES(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            2.0D, 30.0D, 0.5D, 1),
    ASSIMILATION_SELF_RESCUE_QTE_HOLD_CHANCE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SELF_RESCUE_QTE_HOLD_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            4.0D, 100.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_RAPID_CHANCE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SELF_RESCUE_QTE_RAPID_CLICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            2.0D, 8.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_TRACE_CHANCE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1.0D, 0.01D, 2),
    ASSIMILATION_SELF_RESCUE_QTE_TRACE_TIMEOUT_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            20.0D, 400.0D, 5.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_TRACE_NODES(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            2.0D, 16.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_TRACE_SPACING(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            10.0D, 32.0D, 1.0D, 0),
    ASSIMILATION_SELF_RESCUE_QTE_TRACE_HIT_RADIUS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            3.0D, 16.0D, 0.5D, 1),
    ASSIMILATION_SELF_RESCUE_QTE_RANGE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            2.0D, 16.0D, 0.25D, 2),
    ASSIMILATION_RESCUE_GRACE_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_RESCUE,
            0.0D, 1200.0D, 20.0D, 0),

    ASSIMILATION_PARTIAL_PURGE_ENABLED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 1.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_CURSOR_MIN_ONE_WAY_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            6.0D, 200.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_CURSOR_MAX_ONE_WAY_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            6.0D, 240.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_ZONE_MIN_WIDTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.04D, 0.80D, 0.01D, 2),
    ASSIMILATION_PARTIAL_PURGE_ZONE_MAX_WIDTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.04D, 0.90D, 0.01D, 2),
    ASSIMILATION_PARTIAL_PURGE_SUCCESS_AMOUNT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.001D, 1.0D, 0.005D, 3),
    ASSIMILATION_PARTIAL_PURGE_FAILURE_AMOUNT(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 1.0D, 0.005D, 3),
    ASSIMILATION_PARTIAL_PURGE_SUCCESS_WEAKNESS_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 1200.0D, 20.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_FAILURE_WEAKNESS_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 1200.0D, 20.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_FAILURE_DAMAGE(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 20.0D, 0.5D, 1),
    ASSIMILATION_PARTIAL_PURGE_ROUND_COOLDOWN_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 100.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_SPLASH_DROPLETS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 24.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_SPLASH_SPEED(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.01D, 0.50D, 0.01D, 2),

    ASSIMILATION_SCREEN_CRACK_START_PROGRESS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            0.05D, 1.0D, 0.01D, 2),
    ASSIMILATION_SCREEN_CRACK_MIN_INTERVAL_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            4.0D, 600.0D, 4.0D, 0),
    ASSIMILATION_SCREEN_CRACK_MAX_INTERVAL_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            4.0D, 1200.0D, 4.0D, 0),
    ASSIMILATION_SCREEN_CRACK_FADE_IN_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            1.0D, 200.0D, 1.0D, 0),
    ASSIMILATION_SCREEN_CRACK_HOLD_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            1.0D, 1200.0D, 2.0D, 0),
    ASSIMILATION_SCREEN_CRACK_FADE_OUT_TICKS(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            1.0D, 400.0D, 1.0D, 0),
    ASSIMILATION_SCREEN_CRACK_MIN_LENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            0.04D, 0.90D, 0.01D, 2),
    ASSIMILATION_SCREEN_CRACK_MAX_LENGTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            0.04D, 1.10D, 0.01D, 2),
    ASSIMILATION_SCREEN_CRACK_MIN_WIDTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            0.002D, 0.09D, 0.002D, 3),
    ASSIMILATION_SCREEN_CRACK_MAX_WIDTH(Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_CRACKS,
            0.002D, 0.12D, 0.002D, 3),

    // Keep new profile values append-only so old saved per-block arrays remain valid.
    ERUPTION_ENABLED(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_SPAWN_CHANCE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 0.01D, 2),
    ERUPTION_SPAWN_INTERVAL_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            10.0D, 1200.0D, 5.0D, 0),
    ERUPTION_SPAWN_ATTEMPTS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            1.0D, 8.0D, 1.0D, 0),
    ERUPTION_SEARCH_RADIUS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            2.0D, 32.0D, 0.5D, 1),
    ERUPTION_MIN_RADIUS_PIXELS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            2.0D, 12.0D, 0.5D, 1),
    ERUPTION_MAX_RADIUS_PIXELS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            2.0D, 16.0D, 0.5D, 1),
    ERUPTION_MIN_LIFETIME_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            40.0D, 7200.0D, 20.0D, 0),
    ERUPTION_MAX_LIFETIME_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            40.0D, 14400.0D, 20.0D, 0),
    ERUPTION_MIN_BURST_INTERVAL_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            4.0D, 400.0D, 1.0D, 0),
    ERUPTION_MAX_BURST_INTERVAL_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            4.0D, 800.0D, 1.0D, 0),
    ERUPTION_MIN_HEIGHT(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.05D, 2.0D, 0.05D, 2),
    ERUPTION_MAX_HEIGHT(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.05D, 4.0D, 0.05D, 2),
    ERUPTION_MIN_DROPLETS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            1.0D, 48.0D, 1.0D, 0),
    ERUPTION_MAX_DROPLETS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            1.0D, 64.0D, 1.0D, 0),
    ERUPTION_MAX_ACTIVE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 96.0D, 1.0D, 0),
    ERUPTION_MIN_SPACING(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.5D, 12.0D, 0.25D, 2),
    ERUPTION_CONTINUOUS_ENABLED(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_SURGES_ENABLED(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FLOW_INTERVAL_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            1.0D, 40.0D, 1.0D, 0),
    ERUPTION_FLOW_MIN_DROPLETS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            1.0D, 16.0D, 1.0D, 0),
    ERUPTION_FLOW_MAX_DROPLETS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            1.0D, 24.0D, 1.0D, 0),
    ERUPTION_FLOW_HEIGHT_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.10D, 2.0D, 0.05D, 2),
    ERUPTION_POWER_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.25D, 4.0D, 0.05D, 2),
    ERUPTION_VOLUME_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.25D, 4.0D, 0.05D, 2),
    ERUPTION_JET_COHESION(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.0D, 1.0D, 0.05D, 2),
    ERUPTION_TOP_SPREAD_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.10D, 2.0D, 0.05D, 2),
    ERUPTION_SPREAD_TRIGGER_RATIO(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            0.0D, 0.80D, 0.025D, 3),
    ERUPTION_FLOW_MIN_HEIGHT(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.05D, 4.0D, 0.05D, 2),
    ERUPTION_FLOW_MAX_HEIGHT(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.05D, 6.0D, 0.05D, 2),
    ERUPTION_FLOW_VOLUME_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.25D, 4.0D, 0.05D, 2),
    ERUPTION_FLOW_JET_COHESION(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.0D, 1.0D, 0.05D, 2),
    ERUPTION_FLOW_TOP_SPREAD_SCALE(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.10D, 2.0D, 0.05D, 2),
    ERUPTION_FLOW_SPREAD_TRIGGER_RATIO(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            0.0D, 0.80D, 0.025D, 3),
    ERUPTION_SURGE_DURATION_TICKS(Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            1.0D, 20.0D, 1.0D, 0),
    ERUPTION_FLOW_VARIATION_INTERVAL_TICKS(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            5.0D, 400.0D, 5.0D, 0),

    // Gradual fountain breakup. Appended to preserve saved local profile ordinals.
    ERUPTION_FLOW_SPREAD_DURATION_TICKS(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            1.0D, 12.0D, 1.0D, 0),
    ERUPTION_SPREAD_DURATION_TICKS(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SURGES,
            1.0D, 12.0D, 1.0D, 0),

    // Harvest settings. Appended to preserve saved local profile and network ordinals.
    HARVEST_HARDNESS(Target.ALL, Category.HARVEST, 0.05D, 50.0D, 0.05D, 2),
    HARVEST_PREFERRED_TOOL(
            Target.ALL, Category.HARVEST, 0.0D, MudHarvestTool.values().length - 1.0D, 1.0D, 0),
    HARVEST_HAND_SPEED_MULTIPLIER(Target.ALL, Category.HARVEST, 0.0D, 4.0D, 0.05D, 2),
    HARVEST_PREFERRED_TOOL_SPEED_MULTIPLIER(
            Target.ALL, Category.HARVEST, 0.0D, 4.0D, 0.05D, 2),
    HARVEST_OTHER_TOOL_SPEED_MULTIPLIER(Target.ALL, Category.HARVEST, 0.0D, 4.0D, 0.05D, 2),

    // Dropped-item settling. Appended to preserve saved local profile and network ordinals.
    ITEM_PHYSICS_ENABLED(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 1.0D, 0),
    ITEM_MAXIMUM_SINK_DEPTH(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 4.0D, 0.01D, 2),
    ITEM_SETTLING_SPEED(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 0.20D, 0.0005D, 4),
    ITEM_SETTLING_RESPONSE(Target.ALL, Category.DROPPED_ITEMS, 0.01D, 1.0D, 0.01D, 2),
    ITEM_SURFACE_HORIZONTAL_RETENTION(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 0.01D, 2),
    ITEM_SUBMERGED_HORIZONTAL_RETENTION(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 0.01D, 2),
    ITEM_IMPACT_PENETRATION_SCALE(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 0.01D, 2),
    ITEM_MAXIMUM_IMPACT_PENETRATION(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 2.0D, 0.01D, 2),
    ITEM_IMPACT_VELOCITY_RETENTION(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 0.01D, 2),
    ITEM_RELEASE_UPWARD_SPEED(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 0.01D, 2),
    ITEM_STABLE_PRESENTATION_ENABLED(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 1.0D, 1.0D, 0),
    ITEM_PRESENTATION_SETTLE_TICKS(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 40.0D, 1.0D, 0),
    ITEM_PRESENTATION_MAXIMUM_TILT_DEGREES(
            Target.ALL, Category.DROPPED_ITEMS, 0.0D, 45.0D, 1.0D, 0),
    ITEM_BUOYANT_RETURN_SPEED(Target.ALL, Category.DROPPED_ITEMS, 0.0D, 0.20D, 0.0005D, 4),
    ITEM_BUOYANT_RETURN_RESPONSE(Target.ALL, Category.DROPPED_ITEMS, 0.01D, 1.0D, 0.01D, 2),
    ITEM_BUOYANT_RETURN_EASING_DISTANCE(
            Target.ALL, Category.DROPPED_ITEMS, 0.01D, 2.0D, 0.01D, 2),
    ITEM_BUOYANT_RETURN_MAXIMUM_STEP_FRACTION(
            Target.ALL, Category.DROPPED_ITEMS, 0.05D, 0.95D, 0.01D, 2),

    // Finite-volume block flow. Appended to preserve every saved/networked ordinal.
    FLOW_ENABLED(Target.ALL, Category.SHAPE, 0.0D, 1.0D, 1.0D, 0),
    FLOW_INTERVAL_TICKS(Target.ALL, Category.SHAPE, 1.0D, 40.0D, 1.0D, 0),
    FLOW_PIXELS_PER_TRANSFER(Target.ALL, Category.SHAPE, 1.0D, 16.0D, 1.0D, 0),
    FLOW_HORIZONTAL_MINIMUM_PIXELS(Target.ALL, Category.SHAPE, 1.0D, 16.0D, 1.0D, 0),
    FLOW_HORIZONTAL_LEVEL_DIFFERENCE(Target.ALL, Category.SHAPE, 1.0D, 16.0D, 1.0D, 0),
    FLOW_MAXIMUM_SPREAD_DISTANCE(Target.ALL, Category.SHAPE, 1.0D, 64.0D, 1.0D, 0),
    FLOW_MAXIMUM_UPDATES_PER_TICK(Target.ALL, Category.SHAPE, 1.0D, 512.0D, 1.0D, 0),

    // Adaptive coverage texture sampling. Appended to preserve saved/networked ordinals.
    ADAPTIVE_COVERAGE_SMOOTHING_RADIUS(
            Target.ALL, Category.COVERAGE, 0.0D, 3.0D, 1.0D, 0),
    ADAPTIVE_COVERAGE_TEXTURE_DETAIL(
            Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 0.05D, 2),

    // Smooth low-frequency color variation. Appended to preserve saved/networked ordinals.
    COVERAGE_BRIGHTNESS_VARIATION(
            Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 0.01D, 2),

    // Eruption face filters. Appended to preserve saved/networked ordinals.
    ERUPTION_FACE_DOWN_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FACE_UP_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FACE_NORTH_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FACE_SOUTH_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FACE_WEST_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),
    ERUPTION_FACE_EAST_ENABLED(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_SPAWNING,
            0.0D, 1.0D, 1.0D, 0),

    // Adaptive blocks inherit source mining unless this explicit override is enabled.
    HARVEST_OVERRIDE_SOURCE_ENABLED(
            Target.ALL, Category.HARVEST, 0.0D, 1.0D, 1.0D, 0),

    // Independent behavior-template switches. Appended for saved/network ordinal stability.
    COVERAGE_ENABLED(Target.ALL, Category.COVERAGE, 0.0D, 1.0D, 1.0D, 0),
    TENTACLE_ENABLED(Target.TENTACLE, Category.TENTACLE, 0.0D, 1.0D, 1.0D, 0),
    SWARM_ENABLED(Target.SWARM, Category.SWARM, 0.0D, 1.0D, 1.0D, 0),
    SCULK_ENABLED(Target.SCULK, Category.SCULK, 0.0D, 1.0D, 1.0D, 0),
    FLESH_ENABLED(Target.TENDER_FLESH, Category.TENDER_FLESH, 0.0D, 1.0D, 1.0D, 0),

    // Struggle and purge interaction settings. Appended for saved/network ordinal stability.
    STRUGGLE_MAX_COOLDOWN_TICKS(
            Target.ORDINARY, Category.DISTURBANCE, 0.0D, 100.0D, 1.0D, 0),
    SLIME_STRUGGLE_MAX_COOLDOWN_TICKS(
            Target.LIVING_SLIME, Category.SLIME_STRUGGLE, 0.0D, 100.0D, 1.0D, 0),
    ASSIMILATION_PARTIAL_PURGE_CANCEL_ON_MOVE(
            Target.ALL, Category.ASSIMILATION, Subcategory.ASSIMILATION_PURGE,
            0.0D, 1.0D, 1.0D, 0),

    // Continuous-vent visual lifetime. Appended for saved/network ordinal stability.
    ERUPTION_FLOW_PARTICLE_LIFETIME_TICKS(
            Target.ALL, Category.ERUPTION_VENTS, Subcategory.ERUPTION_CONTINUOUS,
            10.0D, 255.0D, 5.0D, 0),

    // Appended for saved/network ordinal stability. Rendered by dedicated depth-mode rows.
    SINKING_DEPTH_CONTROL_MODE(Target.ORDINARY, Category.SINKING, 0.0D, 1.0D, 1.0D, 0),
    SIMPLE_MAXIMUM_SINKING_DEPTH(Target.ORDINARY, Category.SINKING, 0.0D, 1.0D, 0.01D, 2),
    SIMPLE_NATURAL_SINKING_DEPTH(Target.ORDINARY, Category.SINKING, 0.0D, 1.0D, 0.01D, 2),

    // Player auto-step limit while touching ordinary sinking media.
    STEP_HEIGHT(Target.ORDINARY, Category.MOVEMENT, 0.0D, 2.0D, 0.01D, 2),

    // Native block motion. Gravity and finite-volume flow are mutually exclusive.
    GRAVITY_FALLING_ENABLED(Target.ALL, Category.SHAPE, 0.0D, 1.0D, 1.0D, 0);

    public static final int COUNT = values().length;

    private final Target target;
    private final Category category;
    private final Subcategory subcategory;
    private final double minimum;
    private final double maximum;
    private final double step;
    private final int decimals;

    MudPhysicsParameter(Target target, Category category, double minimum, double maximum, double step, int decimals) {
        this(target, category, Subcategory.NONE, minimum, maximum, step, decimals);
    }

    MudPhysicsParameter(Target target, Category category, Subcategory subcategory,
            double minimum, double maximum, double step, int decimals) {
        this.target = target;
        this.category = category;
        this.subcategory = subcategory;
        this.minimum = minimum;
        this.maximum = maximum;
        this.step = step;
        this.decimals = decimals;
    }

    public Target target() {
        return target;
    }

    public Category category() {
        return category;
    }

    public Subcategory subcategory() {
        return subcategory;
    }

    public double minimum() {
        return minimum;
    }

    public double maximum() {
        return maximum;
    }

    public double step() {
        return step;
    }

    public int decimals() {
        return decimals;
    }

    /** Binary profile values are rendered as buttons throughout the tuning UI. */
    public boolean isToggle() {
        return minimum == 0.0D
                && maximum == 1.0D
                && step == 1.0D
                && decimals == 0;
    }

    public boolean isHarvestToolChoice() {
        return this == HARVEST_PREFERRED_TOOL;
    }

    /** Values that render identically are the same user-facing tuning value. */
    public boolean displayEquivalent(double first, double second) {
        if (!Double.isFinite(first) || !Double.isFinite(second)) {
            return Double.doubleToLongBits(first) == Double.doubleToLongBits(second);
        }
        double scale = Math.pow(10.0D, decimals);
        return Math.round(first * scale) == Math.round(second * scale);
    }

    public String serializedName() {
        return name().toLowerCase(java.util.Locale.ROOT);
    }

    public String translationKey() {
        return "gui.mirebound.physics.parameter." + serializedName();
    }

    public double sanitize(double value) {
        if (!Double.isFinite(value)) {
            return minimum;
        }
        return Math.max(minimum, Math.min(maximum, value));
    }

    public boolean appliesTo(SinkingMedium medium) {
        return switch (target) {
            case ALL -> true;
            case ORDINARY -> medium != SinkingMedium.LIVING_SLIME;
            case LIVING_SLIME -> medium == SinkingMedium.LIVING_SLIME;
            case TENTACLE, SWARM, SCULK, TENDER_FLESH ->
                    medium != SinkingMedium.LIVING_SLIME;
        };
    }

    public boolean appliesToAdaptive() {
        return target != Target.LIVING_SLIME
                && this != AUTO_STACK_FILL
                && this != GRAVITY_FALLING_ENABLED
                && !name().startsWith("FLOW_");
    }

    public boolean isFiniteVolumeFlowParameter() {
        return name().startsWith("FLOW_")
                || this == GRAVITY_FALLING_ENABLED;
    }

    public boolean appliesToTentacle() {
        return target == Target.TENTACLE;
    }

    public static MudPhysicsParameter[] forMedium(SinkingMedium medium) {
        return Arrays.stream(values()).filter(parameter -> parameter.appliesTo(medium)).toArray(MudPhysicsParameter[]::new);
    }

    public enum Target {
        ALL,
        ORDINARY,
        LIVING_SLIME,
        TENTACLE,
        SWARM,
        SCULK,
        TENDER_FLESH
    }

    public enum Category {
        SHAPE,
        COVERAGE,
        SINKING,
        MOVEMENT,
        DISTURBANCE,
        SLIME_DEPTH,
        SLIME_BOUNCE,
        SLIME_ANCHOR,
        SLIME_STRUGGLE,
        ADHESION_STRANDS,
        RHEOLOGY,
        TENTACLE,
        TENTACLE_LIFECYCLE,
        TENTACLE_DYNAMICS,
        TENTACLE_PATH,
        TENTACLE_GRAB,
        SWARM,
        SCULK,
        TENDER_FLESH,
        ASSIMILATION,
        BEHAVIOR_COMPONENTS,
        SURFACE_EFFECTS,
        ERUPTION_VENTS,
        HARVEST,
        DROPPED_ITEMS;

        public String translationKey() {
            return "gui.mirebound.physics.category." + name().toLowerCase(java.util.Locale.ROOT);
        }
    }

    public enum Subcategory {
        NONE,
        ASSIMILATION_CORE,
        ASSIMILATION_SOUL,
        ASSIMILATION_RESCUE,
        ASSIMILATION_PURGE,
        ASSIMILATION_CRACKS,
        ERUPTION_SPAWNING,
        ERUPTION_CONTINUOUS,
        ERUPTION_SURGES;

        public String translationKey() {
            return "gui.mirebound.physics.subcategory."
                    + name().toLowerCase(java.util.Locale.ROOT);
        }
    }
}
